name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  # pull_request:
    # branches: [ "master" ]

jobs:

  build:

    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD --password-stdin
    - name: Build the Docker image
      run: docker build -t raydebillion/new_erply .
   # - name: Docker tag
   #   run: docker tag new_erplyapp raydebillion/new_erplyapp
    - name: Push to Dockerhub
      run: docker push raydebillion/new_erply
