name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted
    #runs-on: ubuntu-latest

    steps:
    - name: login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD #--password-stdin
    - name: pull Docker image
      run: sudo docker pull raydebillion/new_erply
    - name: Docker run
      run: sudo docker run -dit -p 8080:8080 --name erplyapp raydebillion/new_erply
